name: Update plan.json and create branch

on:
  repository_dispatch:
    types:
      - tracking_plan_updated

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Testing Inputs
      run: echo ${{ github.event.client_payload }}
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.run_id }}
    - name: Checkout branch
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: ${{ github.run_id }}
    - name: Get Tracking Plan
      uses: fjogeleit/http-request-action@master
      id: configAPIRequest
      env:
        SEGMENT_CONFIG_API_TOKEN: ${{ secrets.SEGMENT_CONFIG_API_TOKEN }}
      with:
        url: https://platform.segmentapis.com/v1beta/workspaces/demo-gh-protocols/tracking-plans/rs_1qwSMNwJ5juNArrpWTraIrLFnrl
        bearerToken: ${{ secrets.SEGMENT_CONFIG_API_TOKEN }}
        method: GET
    - name: Commit Updated Tracking Plan
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        DIRECTORY=./tracking-plans
        FILE=$DIRECTORY/rs_1qwSMNwJ5juNArrpWTraIrLFnrl.json
        echo $FILE
        pwd
        if [ ! -d "$DIRECTORY" ]; then
          mkdir $DIRECTORY
        fi
        if [ -f $FILE ]; then
          echo ${{ steps.configAPIRequest.outputs.response }} > $FILE
        else
          touch $FILE
          echo ${{ steps.configAPIRequest.outputs.response }} > $FILE
        fi
        git add .
        git commit -m "regenerated Segment Tracking Plan"
        git push